# permissions for end users to edit nestedpkis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nestedpki-editor-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - nestedpkis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - nestedpkis/status
  verbs:
  - get
