# permissions for end users to view nestedtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nestedtemplate-viewer-role
rules:
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - nestedtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - nestedtemplates/status
  verbs:
  - get
