# permissions for end users to edit nestedcontrolplanetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nestedcontrolplanetemplate-editor-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - nestedcontrolplanetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - nestedcontrolplanetemplates/status
  verbs:
  - get
